spring.application.name=auth-user-service
# Server settings
server.port=8080

# Database settings (DataSource)
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://auth-db:5432/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT settings
jwt.secret=${JWT_SECRET:rZ5ET8T7nZ8wwczAInOPKfRGNJhIeyUM32b0TVAwzCYweqe21321Dwqe123}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION:3600000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:604800000}